-- Legejo 1.0 schema for SQLite.
--
-- Timestamps are TEXT in ISO 8601 UTC with milliseconds, generated by the
-- application; flags are integers 0/1. Both keep the SQL identical to
-- PostgreSQL.

-- Accounts --------------------------------------------------------------

CREATE TABLE users (
    id             INTEGER PRIMARY KEY,
    username       TEXT NOT NULL UNIQUE COLLATE NOCASE,
    password_hash  TEXT NOT NULL,
    is_admin       INTEGER NOT NULL DEFAULT 0,
    created_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    kobo_token     TEXT,
    locale         TEXT,
    avatar_mime    TEXT,
    email          TEXT,
    -- Pending email verification (self-registration); NULL means verified.
    verify_token   TEXT,
    verify_expires TEXT,
    reset_token    TEXT,
    reset_expires  TEXT,
    -- Pending invitation; the account has an unusable password until accepted.
    invite_token   TEXT,
    invite_expires TEXT,
    kosync_key     TEXT
);
CREATE UNIQUE INDEX idx_users_kobo_token ON users (kobo_token);
CREATE UNIQUE INDEX idx_users_email ON users (lower(email)) WHERE email IS NOT NULL;

CREATE TABLE sessions (
    token      TEXT PRIMARY KEY,
    user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    expires_at TEXT NOT NULL
);
CREATE INDEX idx_sessions_user ON sessions (user_id);

-- One password per reader app; only a SHA-256 of the secret is stored.
CREATE TABLE app_passwords (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id      INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name         TEXT NOT NULL,
    secret_hash  TEXT NOT NULL UNIQUE,
    created_at   TEXT NOT NULL,
    last_used_at TEXT
);
CREATE INDEX idx_app_passwords_user ON app_passwords (user_id);

CREATE TABLE oidc_identities (
    issuer     TEXT NOT NULL,
    subject    TEXT NOT NULL,
    user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TEXT NOT NULL,
    PRIMARY KEY (issuer, subject)
);
CREATE INDEX idx_oidc_identities_user ON oidc_identities (user_id);

-- Failed logins, one row per failure and throttling key.
CREATE TABLE auth_failures (
    id  INTEGER PRIMARY KEY AUTOINCREMENT,
    key TEXT NOT NULL,
    at  TEXT NOT NULL
);
CREATE INDEX idx_auth_failures_key ON auth_failures (key, at);

-- Books ------------------------------------------------------------------

CREATE TABLE books (
    id                 INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid               TEXT NOT NULL UNIQUE,
    owner_id           INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title              TEXT NOT NULL,
    author             TEXT,
    language           TEXT,
    description        TEXT,
    publisher          TEXT,
    -- Edition date, normalized to YYYY, YYYY-MM or YYYY-MM-DD.
    published          TEXT,
    identifier         TEXT,
    category           TEXT,
    isbn               TEXT,
    libris_id          TEXT,
    file_size          INTEGER NOT NULL,
    cover_mime         TEXT,
    created_at         TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at         TEXT,
    -- The book this one was copied from (public shelf import).
    source_uuid        TEXT,
    series             TEXT,
    series_index       REAL,
    rating             BIGINT CHECK (rating BETWEEN 1 AND 5),
    license            TEXT,
    license_source_url TEXT,
    author_death_year  BIGINT,
    cover_is_free      BIGINT NOT NULL DEFAULT 0,
    file_sha256        TEXT,
    -- Object IRI of the federated book this one was imported from.
    fed_source         TEXT,
    kobo_removed_at    TEXT,
    want_to_read       BIGINT NOT NULL DEFAULT 0,
    wanted_at          TEXT,
    first_published    BIGINT,
    -- KOReader's partial MD5 of the file, its document id for kosync.
    koreader_md5       TEXT
);
CREATE INDEX idx_books_owner ON books (owner_id);
CREATE INDEX idx_books_koreader_md5 ON books (koreader_md5);

CREATE TABLE book_tags (
    book_id INTEGER NOT NULL REFERENCES books(id) ON DELETE CASCADE,
    tag     TEXT NOT NULL,
    PRIMARY KEY (book_id, tag)
);
CREATE INDEX idx_book_tags_tag ON book_tags (tag);

-- Full-text search over books, kept in sync by triggers.
CREATE VIRTUAL TABLE books_fts USING fts5(
    title,
    author,
    description,
    category,
    content='books',
    content_rowid='id',
    tokenize='unicode61 remove_diacritics 2'
);

CREATE TRIGGER books_fts_insert AFTER INSERT ON books BEGIN
    INSERT INTO books_fts (rowid, title, author, description, category)
    VALUES (new.id, new.title, new.author, new.description, new.category);
END;

CREATE TRIGGER books_fts_delete AFTER DELETE ON books BEGIN
    INSERT INTO books_fts (books_fts, rowid, title, author, description, category)
    VALUES ('delete', old.id, old.title, old.author, old.description, old.category);
END;

CREATE TRIGGER books_fts_update AFTER UPDATE ON books BEGIN
    INSERT INTO books_fts (books_fts, rowid, title, author, description, category)
    VALUES ('delete', old.id, old.title, old.author, old.description, old.category);
    INSERT INTO books_fts (rowid, title, author, description, category)
    VALUES (new.id, new.title, new.author, new.description, new.category);
END;

-- Shelves ----------------------------------------------------------------

CREATE TABLE shelves (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    owner_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name        TEXT NOT NULL COLLATE NOCASE,
    is_public   INTEGER NOT NULL DEFAULT 0,
    description TEXT,
    cover_mime  TEXT,
    created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at  TEXT,
    visibility  TEXT NOT NULL DEFAULT 'private' CHECK (visibility IN ('private', 'instance', 'federated')),
    -- ActivityPub actor name of a federated shelf.
    ap_slug     TEXT,
    UNIQUE (owner_id, name)
);
CREATE UNIQUE INDEX idx_shelves_ap_slug ON shelves (lower(ap_slug));

CREATE TABLE shelf_books (
    shelf_id INTEGER NOT NULL REFERENCES shelves(id) ON DELETE CASCADE,
    book_id  INTEGER NOT NULL REFERENCES books(id) ON DELETE CASCADE,
    added_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    PRIMARY KEY (shelf_id, book_id)
);
CREATE INDEX idx_shelf_books_book ON shelf_books (book_id);

-- Reading state ----------------------------------------------------------

CREATE TABLE kobo_reading_state (
    user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    book_id    INTEGER NOT NULL REFERENCES books(id) ON DELETE CASCADE,
    state      TEXT NOT NULL,
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    PRIMARY KEY (user_id, book_id)
);

-- Deleted shelves, so the next Kobo sync can remove the collection.
CREATE TABLE kobo_deleted_shelves (
    shelf_id   INTEGER PRIMARY KEY,
    owner_id   INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    deleted_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

-- Position in the web reader.
CREATE TABLE reading_progress (
    user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    book_id    INTEGER NOT NULL REFERENCES books(id) ON DELETE CASCADE,
    cfi        TEXT NOT NULL,
    percent    REAL NOT NULL CHECK (percent >= 0 AND percent <= 1),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    PRIMARY KEY (user_id, book_id)
);

-- KOReader progress, keyed by its document id; book_id is set when the
-- document matches a book in the library.
CREATE TABLE kosync_progress (
    user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    document   TEXT NOT NULL,
    book_id    INTEGER REFERENCES books(id) ON DELETE SET NULL,
    progress   TEXT NOT NULL,
    percentage DOUBLE PRECISION NOT NULL,
    device     TEXT,
    device_id  TEXT,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (user_id, document)
);
CREATE UNIQUE INDEX idx_kosync_user_book ON kosync_progress (user_id, book_id) WHERE book_id IS NOT NULL;

-- Instance ---------------------------------------------------------------

CREATE TABLE settings (
    key   TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

CREATE TABLE activity_log (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    at         TEXT NOT NULL,
    actor_id   INTEGER,
    actor_name TEXT,
    action     TEXT NOT NULL,
    details    TEXT NOT NULL DEFAULT '{}'
);
CREATE INDEX idx_activity_log_action ON activity_log (action);
CREATE INDEX idx_activity_log_actor ON activity_log (actor_id);

CREATE TABLE exports (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id      INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    status       TEXT NOT NULL CHECK (status IN ('queued', 'running', 'done', 'failed', 'expired')),
    total        INTEGER NOT NULL DEFAULT 0,
    done         INTEGER NOT NULL DEFAULT 0,
    bytes        INTEGER NOT NULL DEFAULT 0,
    -- JSON list of {"name": "...", "size": n}
    parts        TEXT NOT NULL DEFAULT '[]',
    error        TEXT,
    worker       TEXT,
    heartbeat_at TEXT,
    created_at   TEXT NOT NULL,
    finished_at  TEXT,
    expires_at   TEXT
);
CREATE INDEX idx_exports_user ON exports (user_id);
CREATE INDEX idx_exports_status ON exports (status);

-- Responses from Libris and Open Library.
CREATE TABLE metadata_cache (
    key        TEXT PRIMARY KEY,
    body       TEXT NOT NULL,
    fetched_at TEXT NOT NULL
);

-- Federation (ActivityPub) -----------------------------------------------

CREATE TABLE ap_keys (
    actor_iri   TEXT PRIMARY KEY,
    public_pem  TEXT NOT NULL,
    private_pem TEXT NOT NULL
);

CREATE TABLE ap_followers (
    shelf_id    INTEGER NOT NULL REFERENCES shelves(id) ON DELETE CASCADE,
    actor_iri   TEXT NOT NULL,
    inbox       TEXT NOT NULL,
    accepted_at TEXT NOT NULL,
    PRIMARY KEY (shelf_id, actor_iri)
);

CREATE TABLE ap_remote_actors (
    iri                TEXT PRIMARY KEY,
    domain             TEXT NOT NULL,
    kind               TEXT,
    preferred_username TEXT,
    name               TEXT,
    summary            TEXT,
    inbox              TEXT,
    shared_inbox       TEXT,
    outbox             TEXT,
    public_pem         TEXT,
    fetched_at         TEXT NOT NULL,
    gone               INTEGER NOT NULL DEFAULT 0,
    -- Reachability of followed shelves.
    checked_at         TEXT,
    unreachable_since  TEXT
);

CREATE TABLE ap_follows (
    user_id          INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    remote_actor_iri TEXT NOT NULL,
    state            TEXT NOT NULL CHECK (state IN ('pending', 'accepted', 'rejected', 'gone')),
    created_at       TEXT NOT NULL,
    -- When the Follow was last sent; NULL while the instance awaits approval.
    sent_at          TEXT,
    PRIMARY KEY (user_id, remote_actor_iri)
);

CREATE TABLE ap_remote_books (
    object_iri         TEXT PRIMARY KEY,
    shelf_actor_iri    TEXT NOT NULL,
    title              TEXT NOT NULL,
    author             TEXT,
    language           TEXT,
    isbn               TEXT,
    summary            TEXT,
    license            TEXT NOT NULL,
    license_source_url TEXT NOT NULL,
    author_death_year  INTEGER,
    epub_url           TEXT NOT NULL,
    epub_sha256        TEXT NOT NULL,
    epub_size          INTEGER NOT NULL,
    cover_url          TEXT,
    published          TEXT,
    received_at        TEXT NOT NULL,
    deleted_at         TEXT
);
CREATE INDEX idx_ap_remote_books_shelf ON ap_remote_books (shelf_actor_iri);

-- Instances waiting for an admin decision in allowlist mode: a remote
-- instance that tried to follow a shelf here ('in'), or a local user who
-- wants to follow a shelf on an instance that is not allowed yet ('out').
CREATE TABLE ap_instance_requests (
    domain       TEXT NOT NULL,
    direction    TEXT NOT NULL CHECK (direction IN ('in', 'out')),
    -- The shelf concerned: a local shelf handle ('in') or a remote shelf ('out').
    detail       TEXT NOT NULL,
    -- The remote actor IRI ('in') or the local username ('out').
    requested_by TEXT NOT NULL,
    attempts     BIGINT NOT NULL DEFAULT 1,
    first_at     TEXT NOT NULL,
    last_at      TEXT NOT NULL,
    PRIMARY KEY (domain, direction, detail, requested_by)
);

CREATE TABLE ap_instances (
    domain       TEXT PRIMARY KEY,
    status       TEXT NOT NULL CHECK (status IN ('allowed', 'blocked', 'relay')),
    relay_actor  TEXT,
    software     TEXT,
    note         TEXT,
    added_by     INTEGER,
    added_at     TEXT NOT NULL,
    last_seen_at TEXT
);

CREATE TABLE ap_deliveries (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    inbox           TEXT NOT NULL,
    actor_iri       TEXT NOT NULL,
    body            TEXT NOT NULL,
    attempts        INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TEXT NOT NULL,
    last_error      TEXT,
    created_at      TEXT NOT NULL
);
CREATE INDEX idx_ap_deliveries_due ON ap_deliveries (next_attempt_at);

CREATE TABLE ap_inbox_seen (
    id      TEXT PRIMARY KEY,
    seen_at TEXT NOT NULL
);

CREATE TABLE ap_published (
    shelf_id     INTEGER NOT NULL,
    book_id      INTEGER NOT NULL,
    book_uuid    TEXT NOT NULL,
    object_hash  TEXT NOT NULL,
    published_at TEXT NOT NULL,
    PRIMARY KEY (shelf_id, book_id)
);

CREATE TABLE ap_rejections (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    at            TEXT NOT NULL,
    activity_type TEXT,
    actor         TEXT,
    domain        TEXT,
    reason        TEXT NOT NULL
);
